/* Seed decks for first-time users. High-frequency English vocabulary with
   examples, pronunciation, and Ukrainian translations. */

window.SEED_DECKS = [
  {
    name: "English · Core Vocabulary",
    desc: "High-frequency words every learner should know first.",
    cards: [
      { front: "ubiquitous",   back: "всюдисущий; повсюди присутній",
        example: "Smartphones are now ubiquitous in modern life.",
        hint: "/juːˈbɪkwɪtəs/" },
      { front: "meticulous",   back: "ретельний, прискіпливий",
        example: "She is meticulous about every detail.",
        hint: "/məˈtɪkjələs/" },
      { front: "resilient",    back: "стійкий, витривалий",
        example: "Children are surprisingly resilient.",
        hint: "/rɪˈzɪliənt/" },
      { front: "compelling",   back: "переконливий; захоплюючий",
        example: "He made a compelling argument.",
        hint: "/kəmˈpelɪŋ/" },
      { front: "endeavor",     back: "(іменник) починання; (дієслово) прагнути",
        example: "We will endeavor to do better next time.",
        hint: "/ɪnˈdevər/" },
      { front: "scrutinize",   back: "ретельно вивчати, перевіряти",
        example: "Auditors scrutinize the financial records.",
        hint: "/ˈskruːtənaɪz/" },
      { front: "ambiguous",    back: "двозначний, неоднозначний",
        example: "His answer was deliberately ambiguous.",
        hint: "/æmˈbɪɡjuəs/" },
      { front: "elaborate",    back: "докладний; деталізувати",
        example: "Could you elaborate on that point?",
        hint: "/ɪˈlæbərət/" },
      { front: "diligent",     back: "старанний, наполегливий",
        example: "She is a diligent student.",
        hint: "/ˈdɪlɪdʒənt/" },
      { front: "feasible",     back: "здійсненний, можливий",
        example: "Is the plan economically feasible?",
        hint: "/ˈfiːzəbəl/" },
      { front: "leverage",     back: "використовувати з вигодою",
        example: "We leverage data to improve products.",
        hint: "/ˈlevərɪdʒ/" },
      { front: "mitigate",     back: "пом'якшувати, зменшувати",
        example: "Plant trees to mitigate climate change.",
        hint: "/ˈmɪtɪɡeɪt/" },
      { front: "concise",      back: "стислий, лаконічний",
        example: "Keep your answer concise.",
        hint: "/kənˈsaɪs/" },
      { front: "redundant",    back: "зайвий; надлишковий",
        example: "Remove redundant sentences from the draft.",
        hint: "/rɪˈdʌndənt/" },
      { front: "pragmatic",    back: "прагматичний, практичний",
        example: "She took a pragmatic approach to the problem.",
        hint: "/præɡˈmætɪk/" },
      { front: "thrive",       back: "процвітати, успішно розвиватися",
        example: "Plants thrive in this climate.",
        hint: "/θraɪv/" },
      { front: "deliberate",   back: "навмисний; обмірковувати",
        example: "It was a deliberate mistake.",
        hint: "/dɪˈlɪbərət/" },
      { front: "tedious",      back: "нудний, виснажливий",
        example: "Filing taxes is a tedious process.",
        hint: "/ˈtiːdiəs/" },
      { front: "indispensable",back: "незамінний, конче необхідний",
        example: "He has become indispensable to the team.",
        hint: "/ˌɪndɪˈspensəbəl/" },
      { front: "comprehend",   back: "розуміти, осягати",
        example: "I can't comprehend his behavior.",
        hint: "/ˌkɑːmprɪˈhend/" }
    ]
  },
  {
    name: "English · Phrasal Verbs",
    desc: "Essential phrasal verbs for fluent conversation.",
    cards: [
      { front: "give up",      back: "здаватися, припиняти спроби",
        example: "Don't give up on your dreams." },
      { front: "look up",      back: "шукати інформацію (у словнику тощо)",
        example: "I'll look up the word in the dictionary." },
      { front: "figure out",   back: "розібратися, зрозуміти",
        example: "Can you figure out this puzzle?" },
      { front: "come up with", back: "придумувати, пропонувати (ідею)",
        example: "She came up with a brilliant idea." },
      { front: "put off",      back: "відкладати, переносити",
        example: "Don't put off until tomorrow what you can do today." },
      { front: "run into",     back: "випадково зустріти",
        example: "I ran into an old friend yesterday." },
      { front: "look forward to", back: "з нетерпінням чекати",
        example: "I look forward to seeing you soon." },
      { front: "get along with", back: "ладнати з кимось",
        example: "She gets along with everyone at work." },
      { front: "turn down",    back: "відхиляти, відмовляти",
        example: "He turned down the job offer." },
      { front: "bring up",     back: "піднімати (тему); виховувати",
        example: "She brought up an interesting point." }
    ]
  },
  {
    name: "English · Idioms",
    desc: "Common English idioms for natural speech.",
    cards: [
      { front: "piece of cake",
        back: "дуже легка справа",
        example: "The exam was a piece of cake." },
      { front: "break the ice",
        back: "розрядити обстановку, познайомитися",
        example: "He told a joke to break the ice." },
      { front: "hit the books",
        back: "інтенсивно вчитися",
        example: "I need to hit the books tonight." },
      { front: "under the weather",
        back: "почуватися погано",
        example: "I'm feeling under the weather today." },
      { front: "cost an arm and a leg",
        back: "коштувати дуже дорого",
        example: "That car costs an arm and a leg." },
      { front: "once in a blue moon",
        back: "дуже рідко",
        example: "I see him once in a blue moon." },
      { front: "spill the beans",
        back: "розкрити секрет",
        example: "Don't spill the beans about the surprise party." },
      { front: "burn the midnight oil",
        back: "працювати до пізньої ночі",
        example: "She burned the midnight oil to finish the report." }
    ]
  }
];
